import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

/**
 * Writes public/sw.js with the offline precache list baked in.
 *
 * Generated rather than hand-written for the same reason imageManifest.ts is:
 * the list has to match what is actually on disk. A precache entry for a file
 * that does not exist makes `cache.addAll` reject, which fails the whole
 * install and leaves the app with no offline support at all — silently.
 *
 * Runs as part of `prebuild`.
 */

const ROOT = process.cwd();
const PUBLIC = path.join(ROOT, "public");
const OUT = path.join(PUBLIC, "sw.js");

/** Directories whose contents are part of the offline shell. */
const PRECACHE_DIRS = ["default-images", "brand"];
const ASSET_EXTENSIONS = new Set([".webp", ".png", ".jpg", ".jpeg", ".svg", ".ico"]);

function listAssets(): string[] {
  const found: string[] = [];
  for (const dir of PRECACHE_DIRS) {
    let entries: string[];
    try {
      entries = readdirSync(path.join(PUBLIC, dir));
    } catch {
      continue;
    }
    for (const entry of entries) {
      if (!ASSET_EXTENSIONS.has(path.extname(entry).toLowerCase())) continue;
      found.push(`/${dir}/${encodeURI(entry)}`);
    }
  }
  return found.sort();
}

function main(): void {
  const assets = listAssets();
  // Version the cache by content so a deploy that changes artwork evicts the
  // old entries instead of serving them forever.
  const version = createHash("sha256").update(assets.join("|")).digest("hex").slice(0, 12);

  const source = `/* GENERATED by scripts/generateServiceWorker.ts - do not edit. */
/*
 * Offline support for BridgeBoard.
 *
 * The product promise is that communication survives failure of the network.
 * Without this the app is a server-rendered page: drop the wifi, reload, and
 * there is no board at all. The manual board needs nothing but bundled
 * artwork, the approved vocabulary and the browser's own speech synthesis, so
 * it can and should keep working with no connection.
 *
 * What is deliberately NOT cached:
 *   /api/*          classification, asset streams, auth and health. A stale
 *                   board is worse than no board, and a cached auth response
 *                   would be a security bug.
 *   signed URLs     Supabase asset links expire; caching them guarantees
 *                   broken images later.
 * Generated images therefore do not work offline. That is correct: the AI
 * side needs the network by definition. The manual board does not.
 */
const VERSION = ${JSON.stringify(version)};
const SHELL_CACHE = \`bridgeboard-shell-\${VERSION}\`;
const RUNTIME_CACHE = \`bridgeboard-runtime-\${VERSION}\`;

/** Bundled artwork and the offline entry point. */
const PRECACHE = ${JSON.stringify(["/", "/manifest.webmanifest", ...assets], null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(SHELL_CACHE);
      // Individually, so one missing file cannot fail the whole install and
      // leave the app with no offline support at all.
      await Promise.all(
        PRECACHE.map((url) =>
          cache.add(new Request(url, { cache: "reload" })).catch(() => undefined),
        ),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys
          .filter((key) => key.startsWith("bridgeboard-") && !key.endsWith(VERSION))
          .map((key) => caches.delete(key)),
      );
      await self.clients.claim();
    })(),
  );
});

function isCacheable(url) {
  if (url.origin !== self.location.origin) return false;
  // Never the API: stale boards, stale auth and expiring signed URLs.
  if (url.pathname.startsWith("/api/")) return false;
  return true;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (!isCacheable(url)) return;

  // Navigations: try the network so a deploy is picked up, fall back to the
  // cached shell so a reload with no signal still reaches the manual board.
  if (request.mode === "navigate") {
    event.respondWith(
      (async () => {
        try {
          const fresh = await fetch(request);
          const cache = await caches.open(SHELL_CACHE);
          cache.put("/", fresh.clone()).catch(() => undefined);
          return fresh;
        } catch {
          const cached = (await caches.match(request)) ?? (await caches.match("/"));
          if (cached) return cached;
          throw new Error("offline and nothing cached");
        }
      })(),
    );
    return;
  }

  // Everything else (bundled artwork, JS, CSS, fonts): cache first. These are
  // content-hashed or versioned, so a stale hit is not a risk.
  event.respondWith(
    (async () => {
      const cached = await caches.match(request);
      if (cached) return cached;
      const response = await fetch(request);
      if (response.ok && response.type === "basic") {
        const cache = await caches.open(RUNTIME_CACHE);
        cache.put(request, response.clone()).catch(() => undefined);
      }
      return response;
    })(),
  );
});
`;

  writeFileSync(OUT, source);
  console.log(`service worker  ${assets.length} assets precached  (version ${version})`);
}

main();
